enum MigrationV1TypeMapping {
    static let propertyTypes: [String: [String]] = [
        "abilitata": ["Bool"],
        "addedBy": ["String"],
        "anno": ["Int"],
        "cancellata": ["Bool"],
        "codice_anno": ["String"],
        "codice_bolletta": ["String"],
        "codice_categoria": ["String"],
        "codice_multimediaBolletta": ["String"],
        "codice_regola": ["String"],
        "codice_setAttributiCustom": ["String"],
        "colore": ["String"],
        "colore2": ["String"],
        "costo": ["Double"],
        "data": ["Date"],
        "dataInizio": ["Date"],
        "dato": ["Double", "UIImage"],
        "descrizione": ["String"],
        "icona": ["UIImage"],
        "importo": ["Double"],
        "media": ["UIImage", "Data"],
        "mediaMediaMensile": ["Double"],
        "mediaMensile": ["Double"],
        "media_kind": ["String"],
        "media_type": ["String"],
        "nome": ["String"],
        "note": ["String"],
        "notification": ["Date"],
        "notificationPriority": ["String"],
        "ordinamento": ["Int"],
        "pagato": ["Bool"],
        "regola": ["String"],
        "tipo": ["String"],
    ]
}